#
# Makefile for nfc devices
#

#obj-$(CONFIG_NFC_PN553_DEVICES)		+= pn553.o
obj-$(CONFIG_LGE_NFC_SN100X)             += sn100x_lge.o
obj-$(CONFIG_LGE_NFC_SN100X)             += cold_reset.o
#ccflags-$(CONFIG_NFC_PN553_DEVICES) := -DDEBUG

